
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 17 20:47:04 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RELGT = 24;
  public static final int RELGTEQ = 25;
  public static final int CONST = 36;
  public static final int CHAR = 9;
  public static final int RELLTEQ = 21;
  public static final int RBR = 4;
  public static final int EQUALS = 14;
  public static final int DOUBLE = 34;
  public static final int INTEGER = 31;
  public static final int REPEAT = 12;
  public static final int INT = 8;
  public static final int RELNEQ = 23;
  public static final int MINUS = 27;
  public static final int WRITE = 17;
  public static final int CHARACTER = 33;
  public static final int SEMICOLON = 15;
  public static final int AND = 19;
  public static final int OR = 18;
  public static final int BOOL = 11;
  public static final int COMMA = 30;
  public static final int RELLT = 20;
  public static final int DIV = 29;
  public static final int UNTIL = 13;
  public static final int PLUS = 26;
  public static final int MAIN = 2;
  public static final int ID = 35;
  public static final int EOF = 0;
  public static final int BOOLEAN = 32;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int LCURLY = 5;
  public static final int RCURLY = 6;
  public static final int REAL = 10;
  public static final int COLON = 7;
  public static final int RELEQ = 22;
  public static final int READ = 16;
  public static final int LBR = 3;
}

